name: Build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        compiler: [gcc-7, gcc-8, gcc-9, gcc-10, clang-9, clang-10]
        bits: [32, 64]
        lto: [LTO=y, LTO=n]

    runs-on: ubuntu-latest

    steps:
    - name: Install
      run: |
        sudo apt-get update -q
        sudo apt-get install ${{ matrix.compiler }}

    - uses: actions/checkout@v2

    - name: Submodules
      run: |
        git submodule update --init tpmlib

    - name: make
      run: |
        make CC=${{matrix.compiler}} 32=${{matrix.bits == 32 && 'y' || 'n'}} ${{matrix.lto}}
        ./extend_lz_only.sh
